### ISSUE TITLE
dataset's website can't  log in

### ISSUE THREAD

**Issue by VLadImirluren** [Haian-Jin/TensoIR#2]
Thanks to your code!!
I am a student in another university and interesting in nerf and computer graphics and want to follow your work.But I have no zju email and can't regist.
Can you share the dataset by other ways?
Thanks!!

**Comment by Haian-Jin** [comment]
Sorry, I didn't realize this problem and I will check on this soon later.

**Comment by VLadImirluren** [comment]
> Sorry, I didn't realize this problem and I will check on this soon later.

还有一个问题，这个代码的多卡训练好像很不好使。。os.environ['world_size']没办法识别到我八张卡。。这个有办法修复吗，我查了好几个办法都不好用

**Comment by Haian-Jin** [comment]
I tried multi-GPU training when I just started this project and it worked well. However, since the per-scene training won't take much time (average training time is 5 hours on a single RTX 2080Ti according to my local experiments), I only trained each scene with one GPU in my latter experiments. As a result, although parts of the code are related to multi-GPU training, I actually never use them and they may not be used and should be deleted. So please just ignore them and begin training with one GPU. I am a little busy recently and may check the multi-GPU training when I am available. But I will fix the data link as soon as possible.

**Comment by VLadImirluren** [comment]
> I tried multi-GPU training when I just started this project and it worked well. However, since the per-scene training won't take much time (average training time is 5 hours on a single RTX 2080Ti according to my local experiments), I only trained each scene with one GPU in my latter experients. As a result, although parts of the code is related to multi-GPU training, I actually never use them and they may can not be used and should be deleted. So please just ignore them and begin training with one GPU. I am a little busy recently and may check the multi-GPU training when I am avaiable. But I will fix the data link as soon as possible.

thanks！！！！

**Comment by Haian-Jin** [comment]
The dataset link in readme file has been updated. Please check whether the problem is solved now.
