### ISSUE TITLE
How can I train real data?

### ISSUE THREAD

**Issue by hongsiyu** [Haian-Jin/TensoIR#6]
Which setting using and what should I be careful?

**Comment by Haian-Jin** [comment]
Thanks for your interest in this work. 
I apologize for the delay in my response. I was occupied with my NeurIPS submission.

Regarding your question, if you only have a set of captured images of your target object under a single unknown lighting condition, then your setting is "Training under single lighting condition." However, I would recommend trying to build your code using the script and dataloader that I provided for NeRF-synthetic data. You can start by checking the code flow for "(Optional) Training for the original NeRF-Synthetic dataset" and then write a dataloader for your own data.

I advise against building your code on "Training under single lighting condition" because the code involves a validation process that requires ground-truth data to compute metrics, which you don't have for real data. However, you can choose to delete the related code so that you can still follow this approach.

Let me know if you have any further questions.

**Comment by hongsiyu** [comment]
Thanks for your reply. I build my code like (Optional) Training for the original NeRF-Synthetic dataset" and trained my own data successfully last week. But I got poor performance in geometry and material estimation. I wonder to know if the method is not suitable for human body?

**Comment by Haian-Jin** [comment]
Sorry that I missed your subsequent reply!
Human body is harder to handle than common objects and I didn't try it before. Can you provide some of your failure cases so I can help to analyze the problems?
