### ISSUE TITLE
Out of memory when training on custom blender scene

### ISSUE THREAD

**Issue by wonjunior** [Haian-Jin/TensoIR#9]
Hi, thank you for this exciting paper.

I was looking to run the training on a custom blender scene. I used the utility files to render the full dataset from a user defined blender file. While I manage to train the full 80k steps on the single light armadillo experiment, I am unable to do so on a custom dataset because of a memory issue (gpu used is also 11GB). This happens at the 10k mark. From what I understand, 10k is when you start upsampling the vector and matrix sizes. Just after the 10k steps, the training fails with an out of memory error. What I don't understand is why this happens on my custom scene while the provide scene works correctly. 

Is this related to the fact the alpha mask is being computed at that point?
Do you have any pointers as what would be causing this issue?

**Comment by Haian-Jin** [comment]
Hi, thanks for your interest in this work!
When the iteration comes to 10k, our method will generate an AlphaMask and then begin the physically-based rendering reconstruction (to reconstruct BRDF). During physically-based rendering reconstruction, we need to sample points along each incident lighting direction to compute visibility and indirect lighting, which will have a large GPU memory cost.

To reduce this cost, the generated alpha mask will be used to skip some sampling 3D points along the incident lighting directions, and at the same time, the visibility and indirect lighting for each incident lighting direction of different surface points that belong to the same batch will be computed chunk by chunk, as shown in: https://github.com/Haian-Jin/TensoIR/blob/main/models/relight_utils.py#L448  , the chunk size is specified by relight_chunk_size (  https://github.com/Haian-Jin/TensoIR/blob/main/opt.py#L180).

Your issue may be because your custom scenes have a lot of sampled points needing to be computed during physically-based reconstruction which does not be filtered by the generated alphaMask , and under this case, my default relight_chunk_size may be too big for your data.

My suggestion is that you can make "relight_chunk_size" ( https://github.com/Haian-Jin/TensoIR/blob/main/opt.py#L180) smaller.

Note that unlike "batch size", smaller "relight_chunk_size" may make the training slightly slower, but won't affect the final reconstruction quality.

**Comment by wonjunior** [comment]
You were indeed right, this scene I was using had a lot more sampled points which meant the training went out of memory from the first pbr reconstruction at 10k. It makes more sense now and I could lower the `relight_chunk_size` to make it fit.
Thank you for your help!
